# Generated by Django 3.0.6 on 2021-04-26 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0002_user_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8)),
                ('market', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='symbol',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='transaction',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investing.Stock'),
        ),
        migrations.AddField(
            model_name='user',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='assets', through='investing.Transaction', to='investing.Stock'),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='users_watching', to='investing.Stock'),
        ),
    ]
