# Generated by Django 3.0.6 on 2021-04-26 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0003_auto_20210426_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ave_price', models.FloatField()),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investing.Stock')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='assets', through='investing.Holding', to='investing.Stock'),
        ),
    ]
