# Generated by Django 3.0.6 on 2021-09-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0004_auto_20210426_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='market',
        ),
    ]
