# Generated by Django 3.0.6 on 2021-09-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0006_auto_20210909_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='closing_price',
            field=models.FloatField(null=True),
        ),
    ]
