# Generated by Django 3.0.6 on 2021-09-11 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0007_holding_closing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL),
        ),
    ]
