# Generated by Django 3.0.6 on 2021-10-18 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0010_auto_20210911_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='holding',
            options={'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterField(
            model_name='holding',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='holdings', through='investing.Label', to='investing.Category'),
        ),
        migrations.AlterField(
            model_name='label',
            name='holding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='investing.Holding'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
